global:
  scrape_interval: 2s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "ping"
    static_configs:
      - targets: ["ping-exporter:8000"]
