services:
  utmstack:
    container_name: utmstack-install
    image: ubuntu:24.04
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - utmstack-data:/opt/utmstack
    command: ["tail", "-f", "/dev/null"]

volumes:
  utmstack-data:
